---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.10

suites:
  - name: default
    run_list:
      - recipe[etherpad-lite::default]
    attributes:
    driver_config:
      network:
      - ["private_network", {ip: "192.168.33.35"}]
